[package]
name = "ccsrs"
version = "0.1.0"
authors = ["Yannick Schillo <yschillo@yansonline.de>"]
edition = "2018"

[lib]
name = "ccsrs"
path = "src/lib.rs"

[[bin]]
name = "ccs"
path = "src/bin/main.rs"

[dependencies]
getopts = "0.2"
rand = "0.6"
