[package]
name = "ccsrs-cli"
version = "0.1.0"
authors = ["Yannick Schillo <yschillo@yansonline.de>"]
edition = "2018"

[[bin]]
name = "ccsrs"
path = "src/main.rs"

[dependencies]
#ccsrs = { path = "../ccsrs" }
ccsrs = { git = "https://github.com/tp971/ccsrs" }
getopts = "0.2"
rand = "0.6"
